name: Collections
version: '${version}'
main: com.blockworlds.collections.Collections
api-version: '1.21'
description: EQ2-style collectibles system for Paper
authors: [BlockWorlds]
website: https://blockworlds.com

folia-supported: true

permissions:
  collections.use:
    description: Basic access to collections
    default: true
  collections.admin:
    description: Administrative commands
    default: op
  collections.craft.goggles:
    description: Can craft Collector's Goggles
    default: true
  collections.craft.mastergoggles:
    description: Can craft Master Collector's Goggles
    default: true
  collections.bypass.goggles:
    description: See all tier collectibles without goggles
    default: op
  collections.bypass.cooldown:
    description: No collection cooldown
    default: op
